apiVersion: apps/v1beta1

kind: Deployment

metadata:
  name: Project
  labels:
    app: project

spec:
  replicas: 1
  template:
    metadata:
      labels:
        project: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
          volumeMounts:
          - name: source-dir
            mountPath: /usr/share/nginx/html
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
          - name: nginx-vhost-config
            mountPath: /etc/nginx/conf.d
          - name: nginx-log
            mountPath: /var/log/nginx
      volumes:
      - name: source-dir
        hostPath:
          path: /path/workspace
      - name: nginx-config
        hostPath:
          path: /path/conf/nginx.conf
      - name: nginx-vhost-config
        hostPath:
          path: /path/conf/conf.d
      - name: nginx-log
        hostPath:
          path: /path/log
         
