apiVersion: v1

kind: Service

metadata:
  name: svc-nginx
  labels:
    svc: nginx

spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  
